### ISSUE TITLE
Documentation doesn't mention installation

### ISSUE THREAD

**Issue by RobCranfill** [CedarGroveStudios/CircuitPython_WaveBuilder#2]
The docs (README.md) don't mention installation of the library for this, but

`circup install cedargrove_wavebuilder`

seems to be necessary. Too obvious, perhaps? (The similar step is, indeed, mentioned for wavestore.)

At any rate, thanks for the good work!

**Comment by CedarGroveStudios** [comment]
Thank you for catching the missing `circup` instructions for `wavebuilder`. 

Ironically, `wavestore` isn't in the Community Bundle yet, so `circup` won't work for that library. Temporarily removed it from the `wavestore` repo readme.
